apiVersion: v1
kind: Secret
metadata:
  name: core-server-secrets
  namespace: enxame
type: Opaque
stringData:
  POSTGRES_USER: "enxame"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: ""
  # Chaves mestres para moderação global (base64 das chaves Ed25519)
  MASTER_PUBLIC_KEYS: ""
