apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enxame

resources:
  - namespace.yaml
  - core-server-configmap.yaml
  - core-server-secrets.yaml
  - core-server-deployment.yaml
  - core-server-service.yaml
  - relay-deployment.yaml
  - relay-service.yaml
  - redis.yaml
  - postgres.yaml

commonLabels:
  app.kubernetes.io/part-of: enxame
  app.kubernetes.io/managed-by: kustomize
